(MAINT) Test alternative retry logic

diff --git a/.github/workflows/module_acceptance.yml b/.github/workflows/module_acceptance.yml
--- a/.github/workflows/module_acceptance.yml
+++ b/.github/workflows/module_acceptance.yml
@@ -132,26 +132,36 @@ jobs:
           bundle env
           echo ::endgroup::
 
-      - name: "Provision environment"
-        run: |
-          if [[ "${{ inputs.kernel_modules }}" == "true" ]] && [[ "${{matrix.platforms.provider}}" =~ docker* ]] ; then
-            DOCKER_RUN_OPTS="docker_run_opts: {'--volume': '/lib/modules/$(uname -r):/lib/modules/$(uname -r)'}"
-          else
-            DOCKER_RUN_OPTS=''
-          fi
-          bundle exec rake "litmus:provision[${{matrix.platforms.provider}},${{ matrix.platforms.image }},$DOCKER_RUN_OPTS]"
-          # Redact password
-          FILE='spec/fixtures/litmus_inventory.yaml'
-          sed -e 's/password: .*/password: "[redacted]"/' < $FILE || true
+      - name: "Provision environment and install Puppet agent"
+        uses: nick-fields/retry@v3
+        with:
+          timeout_minutes: 15
+          max_attempts: 5
+          retry_wait_seconds: 10
+          on_retry_command: |
+            echo "Cleaning up failed environment before retry..."
+            if [[ -f spec/fixtures/litmus_inventory.yaml ]]; then
+              bundle exec rake 'litmus:tear_down' || true
+            fi
+          command: |
+            # Provision environment
+            if [[ "${{ inputs.kernel_modules }}" == "true" ]] && [[ "${{matrix.platforms.provider}}" =~ docker* ]] ; then
+              DOCKER_RUN_OPTS="docker_run_opts: {'--volume': '/lib/modules/$(uname -r):/lib/modules/$(uname -r)'}"
+            else
+              DOCKER_RUN_OPTS=''
+            fi
+            bundle exec rake "litmus:provision[${{matrix.platforms.provider}},${{ matrix.platforms.image }},$DOCKER_RUN_OPTS]"
+            # Redact password
+            FILE='spec/fixtures/litmus_inventory.yaml'
+            sed -e 's/password: .*/password: "[redacted]"/' < $FILE || true
 
-      - name: "Install Puppet agent"
-        run: |
-          if [[ "${{ matrix.collection.version }}" ]] ; then
-            export PUPPET_VERSION=${{ matrix.collection.version }}
-            bundle exec rake 'litmus:install_agent[${{ matrix.collection.collection }}]'
-          else
-            bundle exec rake 'litmus:install_agent[${{ matrix.collection }}]'
-          fi
+            # Install Puppet agent
+            if [[ "${{ matrix.collection.version }}" ]] ; then
+              export PUPPET_VERSION=${{ matrix.collection.version }}
+              bundle exec rake 'litmus:install_agent[${{ matrix.collection.collection }}]'
+            else
+              bundle exec rake 'litmus:install_agent[${{ matrix.collection }}]'
+            fi
 
       - name: "Install module"
         run: |
